### ISSUE TITLE
Smart energy meter 

### ISSUE THREAD

**Issue by Percy-k** [agvdberg/Reading-Eastron-SDM-meter-with-Arduino.ino#1]
Please, we are facing difficulties in the coding aspect. Can you please help us 🙏.
These are the components we are using 
ACS712 Current sensor Electr 30A.
LCD with backup i2c.
Atmega328p microcontroller (arduino uno).
GSM Sim900.

The current sensor in three households separately. 
The function of the meter is that the current sensor will measure the consumption and do the output calculation.
Convert the consumption to currency in terms of what the output is .
The GSM will gather information on the microcontroller and send an  sms to the various parties

**Comment by agvdberg** [comment]
I am sorry, i can not help you with your coding.
My measurement is done by a Eastron-SDM-meter and the technical challenges were to read the values via a modbus interface.
You write you are using a ACS712. That is a whole different device.
Perhaps you can watch video's on this device and how to get data from it.
Like https://youtu.be/d6MnA4aPDag?si=tVgsmepKjb6Eg3OJ
